export const BUILTIN_MENU=[
  {cat:'🍺 Пиво', items:[
    {name:'Hoegarden',price:250},
    {name:'Spaten',price:300},
    {name:'Corona Extra',price:300},
    {name:'Stella Artois',price:250},
    {name:'Сидр Chester',price:250},
    {name:'Безалкогольное пиво',price:200},
    {name:'Козел тёмный',price:250},
  ]},
  {cat:'🍵 Фрукт. чай', items:[
    {name:'Облепиховый чай',price:700},
    {name:'Имбирно-лимонный чай',price:700},
    {name:'Вишневый блик',price:700},
    {name:'Облепиха-груша',price:700},
    {name:'Сладкий цитрус',price:700},
    {name:'Итальянские каникулы',price:700},
    {name:'Ягодный микс',price:700},
    {name:'Апельсин-корица',price:700},
    {name:'Имбирно-малиновый чай',price:700},
    {name:'Марокканский чай',price:700},
    {name:'Малиновый чай',price:700},
    {name:'Клюквенный чай',price:700},
  ]},
  {cat:'🍃 Лист. чай', items:[
    {name:'Сенча',price:500},
    {name:'Ассам',price:500},
    {name:'Чай с бергамотом',price:500},
    {name:'Наглый фрукт',price:500},
    {name:'Каркаде',price:500},
    {name:'Клубника со сливками',price:500},
    {name:'Иван-чай',price:500},
  ]},
  {cat:'🥤 Лимонады', items:[
    {name:'Лимонад вишневый',price:400},
    {name:'Манго Давида',price:400},
    {name:'Клубнично-малиновый',price:400},
    {name:'Лимонад цитрусовый',price:400},
    {name:'Лимонад имбирно-лимонный',price:400},
    {name:'Тропический',price:400},
    {name:'Мохито',price:400},
    {name:'Клюква с черной смородиной',price:400},
    {name:'Грейпфрут-ваниль',price:400},
  ]},
  {cat:'🥤 Напитки', items:[
    {name:'Сок',price:400,note:true,notePlaceholder:'какой сок'},
    {name:'Вода газ',price:150},
    {name:'Вода без газа',price:150},
    {name:'Натахтари',price:250,note:true,notePlaceholder:'вкус: виноград, фейхоа, ...'},
    {name:'Red Bull',price:300},
    {name:'Coca-Cola',price:250},
    {name:'Fanta',price:250},
    {name:'Sprite',price:250},
  ]},
  {cat:'🍟 Закуски', items:[
    {name:'Чипсы Lays',price:200},
    {name:'Сухарики',price:200},
    {name:'Фисташки',price:200},
    {name:'Арахис',price:150},
    {name:'Шоколад',price:200,note:true,notePlaceholder:'какой шоколад'},
    {name:'Джерки',price:250},
  ]},
  {cat:'☕ Кофе', items:[
    {name:'Эспрессо',price:100},
    {name:'Двойной эспрессо',price:170},
    {name:'Американо',price:200},
    {name:'Латте',price:350},
    {name:'Капучино',price:350},
  ]},
];
